重构rule_list.lua、其他一些小修复 重构rule_list.lua、减少了初始化脚本的I/O操作。

diff --git a/luci-app-mosdns/root/etc/init.d/mosdns b/luci-app-mosdns/root/etc/init.d/mosdns
--- a/luci-app-mosdns/root/etc/init.d/mosdns
+++ b/luci-app-mosdns/root/etc/init.d/mosdns
@@ -71,12 +71,24 @@ delcron() {
 }
 
 adblock() {
-  cp -f /etc/mosdns/rule/serverlist.txt /etc/mosdns/rule/serverlist.bak
-  modns_adblock=$(uci -q get mosdns.mosdns.adblock)
-  if [ "$modns_adblock" -eq 0 ]; then
-    : > /etc/mosdns/rule/serverlist.txt
+  local mosdns_adblock=$(uci -q get mosdns.mosdns.adblock)
+  local serverlist_act="/etc/mosdns/rule/serverlist.act"
+  local serverlist_txt="/etc/mosdns/rule/serverlist.txt"
+
+  if [ "$mosdns_adblock" -ne 0 ]; then
+    if [ ! -L "$serverlist_act" ] || [ "$(readlink -f "$serverlist_act")" != "$serverlist_txt" ]; then
+      ln -sf "$serverlist_txt" "$serverlist_act" || {
+        echo "Failed to create symbolic link."
+        return 1
+      }
+    fi
   else
-    cat /etc/mosdns/rule/serverlist.bak > /etc/mosdns/rule/serverlist.txt
+    if [ ! -L "$serverlist_act" ] || [ "$(readlink -f "$serverlist_act")" != "/dev/null" ]; then
+      ln -sf /dev/null "$serverlist_act" || {
+        echo "Failed to create symbolic link."
+        return 1
+      }
+    fi
   fi
 }
 
@@ -96,7 +108,7 @@ start_service() {
   # Reading config
   inital_conf
   if [ "$enabled" -eq 0 ]; then
-    printf "MosDNS has turned off\n"
+    printf "MosDNS has been turned off\n"
     return 1
   fi
   delcron
@@ -126,22 +138,20 @@ start_service() {
     restart_others
   fi
 
-  printf "MosDNS turn on\n"
+  printf "MosDNS turned on\n"
   printf "enabled=%d\n" "$enabled"
 }
 
 stop_service() {
+  inital_conf
   pgrep -f /usr/bin/mosdns | xargs kill -9
-  printf "MosDNS turn off\n"
-  printf "enabled=%d\n" "$enabled"
-
   if [ "$(uci -q get mosdns.mosdns.configfile)" = "./def_config.yaml" ]; then
-    config_load "mosdns"
-    enabled=$(uci -q get mosdns.mosdns.enabled)
     if [ "$enabled" = "0" ] && [ "$(uci -q get dhcp.@dnsmasq[0].setbymosdns)" -eq 1 ]; then
       restore_setting
     fi
     restart_others
   fi
   delcron
+  printf "MosDNS turned off\n"
+  printf "enabled=%d\n" "$enabled"
 }
